#!/bin/bash
echo "🔍 Checking Vercel Deployment Status"
echo "===================================="
echo ""
echo "1. Check Vercel Dashboard:"
echo "   https://vercel.com/androidinternals-projects/android-internals/deployments"
echo ""
echo "2. Click on latest deployment"
echo ""
echo "3. Check 'Functions' tab:"
echo "   - Should see: api/auth-github.js"
echo "   - Should see: api/emailjs-contacts.js"
echo "   - Should see: api/subscribers-db.js"
echo ""
echo "4. If functions are NOT listed:"
echo "   - Functions might not be deployed"
echo "   - Check build logs for errors"
echo "   - Verify api/ directory is in repository"
echo ""
echo "5. Get your actual Vercel URL:"
echo "   - In deployment, check 'Domains' section"
echo "   - Or check project overview page"
echo ""
echo "6. Test the URL:"
echo "   curl -I https://YOUR_VERCEL_URL/api/auth-github?action=login"
echo ""
